### ISSUE TITLE
Does the Kappa parameter for KLL determine the number of retained elements?

### ISSUE THREAD

**Issue by thvasilo** [apache/incubator-datasketches-java-new#257]
AFAIK KLL uses a cascade of compactors to produce its interval estimates.

What I'm wondering is what exactly is the effect of the K parameter. Does setting K to a specific value mean that overall, that many values will be retained between all the compactors?

Or does K indicate some other aspect of the sketch? In that case, is it actually possible to determine how many values are being retained in the compactors?

**Comment by AlexanderSaydakov** [comment]
I would suggest viewing K as a parameter that controls the size-vs-accuracy tradeoff. It does not directly translate to the number of retained values.
You can always find out exactly how many values are retained in the sketch at some particular moment by calling getNumRetained().
You may want to have a look at the plots here:
https://datasketches.github.io/docs/Quantiles/KLLSketch.html
One of the plots shows how the number of retained values grows with the number of input values (called stream size in the description of the plot) for K=200 (default). We can see that the number of retained values keeps growing, but very slowly (logarithmically). Very approximately it stays around 3*K for large streams.

**Comment by thvasilo** [comment]
Thank you @AlexanderSaydakov this clarifies the role of K for me.
